---
- name: Install sshfs (debian)
  package:
    cache_valid_time: '{{60*60}}'
    update_cache: yes
    name: "{{item}}"
    state: installed
  with_items: [sshfs]
  when: "ansible_os_family.lower() in ['debian']"
  tags: [cops_sshfs]
  become: true
- name: Install sshfs (redhat)
  package:
    update_cache: yes
    enablerepo: epel-testing
    name: 'yum-utils'
    state: present
  with_items: [sshfs]
  when: "ansible_os_family.lower() in ['redhat']"
  tags: [cops_sshfs]
  become: true
