---
- name: root ssh directory
  file:
    state: directory
    mode: "0700"
    path: /root/.ssh
  tags: [cops_rootsshkeys]
  become: true
- shell: |-
    for i in ubuntu vagrant;do
      ls -1 /home/$i/.ssh/authorized_key* 2>/dev/null
    done
  register: cops_homes
  changed_when: false
  failed_when: false
  tags: [cops_rootsshkeys]
- shell: cat "{{item}}"
  with_items: "{{cops_homes.stdout.splitlines()}}"
  changed_when: false
  register: cops_homesc
  tags: [cops_rootsshkeys]
#- {debug: "msg={{cops_homesc}}", when: vboxes_cops.DEBUG}
- name: Synchronise vagrant home ssh keys to root
  blockinfile:
    path: "/root/.ssh/authorized_keys"
    marker: "# -- {mark} ANSIBLE MANAGED BLOCK --"
    create: true
    mode: "0600"
    insertafter: EOF
    content: |
      {% for i in cops_homesc.results %}
      {{i.stdout}}
      {% endfor %}
  become: true
  tags: [cops_rootsshkeys]
