# -*- mode: ruby -*-
ABSFILE = File.absolute_path(__FILE__)
ABSDIR = File.dirname(ABSFILE)
COPS_DIR = File.join(ABSDIR, "local/corpusops.bootstrap")

# Edit this to the place of the corpusops vagrantfile
require "#{COPS_DIR}/hacking/vagrant/Vagrantfile_common.rb"

# load config
cfg = cops_init(:cwd => ABSDIR, :cops_path => COPS_DIR)

## install corpusops flavored ansible on local box
cfg = cops_install(cfg)

# add here post pre modification like names, subnet, etc
cfg = cops_configure(cfg)

# add here post common modification like modifying played ansible playbooks

# install rancher server only on first box
cfg = cops_inject_playbooks(cfg, [
    # ADD HERE YOUR PLAYBOOKS
    # {"#{cfg['CWD']}/playbooks/xxx.yml" => {}},
])
# vim: set ft=ruby ts=2 et sts=2 tw=0 ai:
