#!/usr/bin/env bash
COPS_VAGRANT_DIR=${COPS_VAGRANT_DIR:-$(readlink -f $(dirname "$(readlink -f "$0")/.."))}
. "$COPS_VAGRANT_DIR/common.sh" || exit 1
. "/root/vagrant/provision_settings.sh" || exit 1
cd "$W"


SKIP_ROOTSSHKEYS_SYNC=${SKIP_ROOTSSHKEYS_SYNC:-}
FORCE_COPS_SYNC=${FORCE_COPS_SYNC:-}


usage () {
    NO_HEADER=y die '
Provision a vagrant vm

[SKIP_ROOTSSHKEYS_SYNC] \
    '"$0"'
'
}


parse_cli() {
    parse_cli_common "${@}"
}

configure_net() {
    echo '#{hostname}' > /etc/hostname
    hostname '#{hostname}'
    sed -i -re "/::1 .*(localhost|#{fqdn}|#{hostname}).*/d" /etc/hosts
    sed -i -re "/127.0.0.1 .*(localhost|#{fqdn}|#{hostname}).*/d" /etc/hosts
    sed -i '1i::1 #{fqdn} #{hostname}' /etc/hosts
    sed -i '1i127.0.0.1 #{fqdn} #{hostname}' /etc/hosts
    echo "::1 #{fqdn} #{hostname}" >> /etc/hosts
    echo "127.0.0.1 #{fqdn} #{hostname}" >> /etc/hosts
    sed -i -re "/^nameserver /d" /etc/resolv.conf
    for i in \\$DNS_SERVERS;do
        echo "nameserver \\$i" >>  /etc/resolv.conf
    done
}

parse_cli "$@"
configure_net || die_in_error configure_net
# vim:set et sts=4 ts=4 tw=80:
