#!/usr/bin/env bash
COPS_VAGRANT_DIR=${COPS_VAGRANT_DIR:-$(readlink -f $(dirname "$(readlink -f "$0")/.."))}
. "$COPS_VAGRANT_DIR/common.sh" || exit 1
cd "$W"


SKIP_ROOTSSHKEYS_SYNC=${SKIP_ROOTSSHKEYS_SYNC:-}
FORCE_COPS_SYNC=${FORCE_COPS_SYNC:-}


usage () {
    NO_HEADER=y die '
Provision a vagrant vm

[SKIP_ROOTSSHKEYS_SYNC] \
    '"$0"'
'
}


parse_cli() {
    parse_cli_common "${@}"
}


sync_ssh() {
    if [[ -n "${SKIP_ROOTSSHKEYS_SYNC}" ]];then
        log "Skip ssh keys sync to root user"
        return 0
    fi
    log "Synchronising user authorized_keys to root"
    if [ ! -e /root/.ssh ];then
        mkdir /root/.ssh
        chmod 700 /root/.ssh
    fi
    fics=""
    users="ubuntu vagrant"
    for u in ${users};do
        for i in $(ls /home/${u}/.ssh/authorized_key* 2>/dev/null);do
            fics="${fics} ${i}"
        done
    done
    if [ "x${fics}" != "x" ];then
        echo > /root/.ssh/authorized_keys
        for i in ${fics};do
            cat ${i} >> /root/.ssh/authorized_keys
            echo >> /root/.ssh/authorized_keys
        done
    fi
}


parse_cli "$@"
sync_ssh          || die_in_error sync_ssh
# vim:set et sts=4 ts=4 tw=80:
