#!/usr/bin/env bash
COPS_VAGRANT_DIR=${COPS_VAGRANT_DIR:-$(readlink -f $(dirname "$(readlink -f "$0")/.."))}
. "$COPS_VAGRANT_DIR/common.sh" || exit 1
cd "$W"


FORCE_COPS_INSTALL=${FORCE_COPS_INSTALL:-}
FORCE_COPS_SYNC=${FORCE_COPS_SYNC:-}


usage () {
    NO_HEADER=y die '
Provision a vagrant vm

[FORCE_COPS_SYNC] \
[FORCE_COPS_INSTALL] \
[SKIP_COPS_SYNC] \
[SKIP_COPS_INSTALL] \
    '"$0"'
'
}


parse_cli() {
    parse_cli_common "${@}"
}


sync_corpusops() {
    if [[ -n "${SKIP_COPS_SYNC}" ]];then
        log "Force skip sync corpusops"
        return 0
    fi
    if [[ -e "$COPS_ROOT/bin/install.sh" ]];then
        if [[ -n $FORCE_COPS_SYNC ]]; then
            vv "$COPS_ROOT/bin/install.sh" -C -s
            die_in_error "sync"
        else
            log "Skip corpusops sync"
        fi
    else
        log "Skip corpusops sync, installer not found in $COPS_ROOT"
    fi
}


install_corpusops() {
    if [[ -n "${SKIP_COPS_INSTALL}" ]];then
        log "Force skip install"
        return 0
    fi
    # in vagrant try to copy the code from the host inside the VM
    if [ -e "$HOST_COPS/.git" ];then
        rsync -azv --exclude=venv "$HOST_COPS/" "$COPS_ROOT/"
    fi
    if [ ! -e "$COPS_ROOT/.git" ] && [[ -n "$COPS_URL" ]] ;then
        git clone "$COPS_URL" "$COPS_ROOT"
    fi
    if [ ! -e "$COPS_ROOT/venv/bin/ansible" ] ||\
        ! ( has_command virtualenv ) ;then
        FORCE_COPS_INSTALL=1
    fi
    if      [ ! -e "$COPS_ROOT/roles/corpusops.roles" ] \
        ||  [ ! -e "$COPS_ROOT/venv/src/ansible" ] \
        ||  [ ! -e "$COPS_ROOT/playbooks/corpusops" ] \
        ||  [ ! -e "$COPS_ROOT/venv/bin/ansible" ]; then
        FORCE_COPS_SYNC=y
    fi
    if [[ -n $FORCE_COPS_INSTALL ]]; then
        vv "$COPS_ROOT/bin/install.sh" -C -S
        die_in_error "install core"
    else
        log "Skip corpusops install"
    fi
}


parse_cli "$@"
install_corpusops || die_in_error install_corpusops
sync_corpusops    || die_in_error sync_corpusops
# vim:set et sts=4 ts=4 tw=80:
