#!/usr/bin/env bash
COPS_VAGRANT_DIR=${COPS_VAGRANT_DIR:-$(readlink -f $(dirname "$(readlink -f "$0")/.."))}
. "$COPS_VAGRANT_DIR/common.sh" || exit 1
cd "$W"

SKIP_SSHFS_INSTALL=${SKIP_SSHFS_INSTALL-}

usage () {
    NO_HEADER=y die '
Provision a vagrant vm

[SKIP_SSHFS_INSTALL] \
    '"$0"'
'
}


parse_cli() {
    parse_cli_common "${@}"
}


install_sshfs() {
    if [[ -n "${SKIP_SSHFS_INSTALL}" ]];then
        log "Force skip install sshfs"
        return 0
    fi
    if ! has_command sshfs;then
        log "Install sshfs"
        NONINTERACTIVE=y "$COPS_ROOT/bin/cops_pkgmgr_install.sh" sshfs
    else
        log "sshfs is installed"
    fi
}


parse_cli "$@"
install_sshfs     || die_in_error install_sshfs
# vim:set et sts=4 ts=4 tw=80: 
