#!/usr/bin/env bash


# scripts vars
SCRIPT=$0
LOGGER_NAME=${LOGGER_NAME-$(basename $0)}
SCRIPT_NAME=$(basename "${SCRIPT}")
SCRIPT_DIR=$(cd "$(dirname $0)" && pwd)
# OW: from where script was called (must be defined from callee)
OW="${OW:-$(pwd)}"
# W is script_dir/..
W=${W:-$(cd "$SCRIPT_DIR/.." && pwd)}
# colors
RED="\\e[0;31m"
CYAN="\\e[0;36m"
YELLOW="\\e[0;33m"
NORMAL="\\e[0;0m"
NO_COLOR=${NO_COLORS-${NO_COLORS-${NOCOLOR-${NOCOLORS-}}}}
LOGGER_NAME=${LOGGER_NAME:-corpusops_build}
ERROR_MSG="There were errors"
do_trap_() { rc=$?;func=$1;sig=$2;${func};if [ "x${sig}" != "xEXIT" ];then kill -${sig} $$;fi;exit $rc; }
do_trap() { rc=${?};func=${1};shift;sigs=${@};for sig in ${sigs};do trap "do_trap_ ${func} ${sig}" "${sig}";done; }
parse_cli() { parse_cli_common "${@}"; }
parse_cli_common() {
    USAGE=
    for i in ${@-};do
        case ${i} in
            --no-color|--no-colors|--nocolor|--no-colors)
                NO_COLOR=1;;
            -h|--help)
                USAGE=1;;
            *) :;;
        esac
    done
    reset_colors
    if [[ -n ${USAGE} ]]; then
        usage
    fi
}
log_() {
    reset_colors;msg_color=${2:-${YELLOW}};
    logger_color=${1:-${RED}};
    logger_slug="${logger_color}[${LOGGER_NAME}]${NORMAL} ";
    shift;shift;
    if [[ -n ${NO_LOGGER_SLUG} ]];then logger_slug="";fi
    printf "${logger_slug}${msg_color}$(echo "${@}")${NORMAL}\n" >&2;
    printf "" >&2;  # flush
}
reset_colors() { if [[ -n ${NO_COLOR} ]];then BLUE="";YELLOW="";RED="";CYAN="";fi; }
log() { log_ "${RED}" "${CYAN}" "${@}"; }
get_chrono() { date "+%F_%H-%M-%S"; }
cronolog() { log_ "${RED}" "${CYAN}" "($(get_chrono)) ${@}"; }
debug() { if [[ -n "${DEBUG// }" ]];then log_ "${YELLOW}" "${YELLOW}" "${@}"; fi; }
warn() { log_ "${RED}" "${CYAN}" "${YELLOW}[WARN] ${@}${NORMAL}"; }
bs_log(){ log_ "${RED}" "${YELLOW}" "${@}"; }
bs_yellow_log(){ log_ "${YELLOW}" "${YELLOW}" "${@}"; }
may_die() {
    reset_colors
    thetest=${1:-1}
    rc=${2:-1}
    shift
    shift
    if [ "x${thetest}" != "x0" ]; then
        if [[ -z "${NO_HEADER-}" ]]; then
            NO_LOGGER_SLUG=y log_ "" "${CYAN}" "Problem detected:"
        fi
        NO_LOGGER_SLUG=y log_ "${RED}" "${RED}" "$@"
        exit $rc
    fi
}
die() { may_die 1 1 "${@}"; }
die_in_error_() {
    ret=${1}; shift; msg="${@:-"$ERROR_MSG"}";may_die "${ret}" "${ret}" "${msg}";
}
die_in_error() { die_in_error_ "${?}" "${@}"; }
has_command() {
    ret=1
    if which which >/dev/null 2>/dev/null;then
      if which "${@}" >/dev/null 2>/dev/null;then
        ret=0
      fi
    else
      if command -v "${@}" >/dev/null 2>/dev/null;then
        ret=0
      else
        if hash -r "${@}" >/dev/null 2>/dev/null;then
            ret=0
        fi
      fi
    fi
    return ${ret}
}
pipe_return() {
    local filter=$1;shift;local command=$@;
    (((($command; echo $? >&3) | $filter >&4) 3>&1) | (read xs; exit $xs)) 4>&1;
}
output_in_error() { ( do_trap output_in_error_post EXIT TERM QUIT INT;\
                      output_in_error_ "${@}" ; ); }
output_in_error_(){
    if [[ -n ${OUTPUT_IN_ERROR_DEBUG-} ]];then set -x;fi
    if [[ -n $TRAVIS ]] || [[ -n $GITLAB_CI ]];then
        DEFAULT_CI_BUILD=y
    fi
    CI_BUILD="${CI_BUILD-${DEFAULT_CI_BUILD-}}"
    if [[ -n $CI_BUILD ]];then
        DEFAULT_NO_OUTPUT=y
        DEFAULT_DO_OUTPUT_TIMER=y
    fi
    VERBOSE="${VERBOSE-}"
    TIMER_FREQUENCE="${TIMER_FREQUENCE:-120}"
    NO_OUTPUT="${NO_OUTPUT-${DEFAULT_NO_OUTPUT-1}}"
    DO_OUTPUT_TIMER="${DO_OUTPUT_TIMER-$DEFAULT_DO_OUTPUT_TIMER}"
    LOG=${LOG-}
    if [[ -n $NO_OUTPUT ]];then
        if [[ -z "${LOG}" ]];then
            LOG=$(mktemp)
            DEFAULT_CLEANUP_LOG=y
        else
            DEFAULT_CLEANUP_LOG=
        fi
    else
        DEFAULT_CLEANUP_LOG=
    fi
    CLEANUP_LOG=${CLEANUP_LOG:-${DEFAULT_CLEANUP_LOG}}
    if [[ -n $VERBOSE ]];then
        log "Running$([[ -n $LOG ]] && echo "($LOG)"; ): $@";
    fi
    TMPTIMER=
    if [[ -n ${DO_OUTPUT_TIMER} ]]; then
        TMPTIMER=$(mktemp)
        ( i=0;\
          while test -f $TMPTIMER;do\
           i=$((++i));\
           if [ `expr $i % $TIMER_FREQUENCE` -eq 0 ];then \
               log "BuildInProgress$([[ -n $LOG ]] && echo "($LOG)"; ): ${@}";\
             i=0;\
           fi;\
           sleep 1;\
          done;\
          if [[ -n $VERBOSE ]];then log "done: ${@}";fi; ) &
    fi
    if [[ -n $NO_OUTPUT ]];then
        "${@}" >>"$LOG" 2>&1;ret=$?
    else
        if [[ -n $LOG ]] && has_command tee;then
            pipe_return "tee -a $LOG" "${@}";ret=$?
        else
            "${@}";ret=$?
        fi
    fi
    if [[ -e "$TMPTIMER" ]]; then rm -f "${TMPTIMER}";fi
    if [[ -z ${OUTPUT_IN_ERROR_NO_WAIT-} ]];then wait;fi
    if [ -e "$LOG" ] &&  [[ "${ret}" != "0" ]] && [[ -n $NO_OUTPUT ]];then
        cat "$LOG" >&2
    fi
    if [[ -n ${OUTPUT_IN_ERROR_DEBUG-} ]];then set +x;fi
    return ${ret}
}
output_in_error_post() {
    if [[ -e "$TMPTIMER" ]]; then rm -f "${TMPTIMER}";fi
    if [[ -e "$LOG" ]] && [[ -n $CLEANUP_LOG ]];then rm -f "$LOG";fi
}
test_silent_log() { ( [[ -z ${NO_SILENT-} ]] && ( [[ -n ${SILENT_LOG-} ]] || [[ -n "${SILENT_DEBUG}" ]] ) ); }
test_silent() { ( [[ -z ${NO_SILENT-} ]] && ( [[ -n ${SILENT-} ]] || test_silent_log ) ); }
silent_run_() { (LOG=${SILENT_LOG:-${LOG}};NO_OUTPUT=;\
                 if test_silent;then NO_OUTPUT=y;fi;output_in_error "$@";) }
silent_run() { ( silent_run_ "${@}" ; ); }
run_silent() { SILENT=${SILENT-1} silent_run "${@}"; }
vvv() { debug "${@}";silent_run "${@}"; }
vv() { log "${@}";silent_run "${@}";}
silent_vv() { SILENT_LOG=${SILENT_LOG-} SILENT=${SILENT-1} vv "${@}"; }
get_full_chrono() { date "+%F_%H-%M-%S-%N"; }
get_git_changeset() { ( cd "${1:-$(pwd)}" && git log HEAD|head -n1|awk '{print $2}'); }
get_git_branch() {
   ( cd "${1:-$(pwd)}" &&\
     git rev-parse --abbrev-ref HEAD | grep -v HEAD || \
     git describe --exact-match HEAD 2> /dev/null || \
     git rev-parse HEAD)
}
get_git_branchs() { ( cd "${1:-$(pwd)}" && git branch|sed -e "s/^\*\? \+//g"); }
get_images() { docker images --no-trunc -q "${@}" 2>/dev/null|awk '!seen[$0]++'; }
get_image() { get_images "${@}" | head -n 1; }

usage() {
    NO_HEADER=y die '
Release images to docker

 [OUTPUT_IN_ERROR=] \
 [FORCE_RELEASE=] \
 [DOCKER_RELEASER=xxx] \
 [DOCKER_PASSWORD=xxx] \
 [RELEASABLE_BRANCHES=xxx] \
 [DOCKER_USER=xxx] \
 [NOCOLOR=y] \
 [DEBUG=y] \
    '"$0"' WORKING_DIR <image> <image1>
 '
}

parse_cli() {
    parse_cli_common "${@}";
    [[ -z $DOCKER_RELEASER ]] && die "no DOCKER_RELEASER"
    [[ -z $DOCKER_PASSWORD ]] && die "no DOCKER_PASSWORD"

    if [[ -n ${1-} ]] && [ -d "${1}" ]; then
        RELEASED_DIR=${1}
        shift
    else
        RELEASED_DIR=${W}
    fi
    R_IMAGES="${@:-"${IMAGES}"}"
    R_IMAGES="$(echo "$R_IMAGES"|xargs -n1|awk '!seen[$0]++')"
    RELEASABLE=""
    for img in ${R_IMAGES};do
        fimg=${img}
        if echo ${fimg} | grep -vq /;then
            if [[ -z $DOCKER_USER ]];then
                die "no DOCKER_USER for $fimg"
            else
                fimg=${DOCKER_USER}/${img}
            fi
        fi
        tagid=$(get_image "${fimg}")
        if [ "x${tagid}" != "x" ]; then
            RELEASABLE="${RELEASABLE} ${fimg}"
        fi
    done
    RELEASABLE="$(echo "${RELEASABLE}" | xargs -n1)"
    RELEASABLE_BRANCHES="${RELEASABLE_BRANCHES:-"^master$"}"
    if [[ -z "${RELEASABLE}" ]]; then
        die "no releasable images produced yet from: ${YELLOW}$IMAGES"
    fi
}

release_test() {
    if [[ -n ${TRAVIS} ]]; then
        if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]];then
            debug "Is a travis pull request, no release"
            return 1
        elif echo "${TRAVIS_BRANCH}"\
            | egrep -iq ${RELEASABLE_BRANCHES}; then
            return 0
        fi
    else
        if [[ -n ${FORCE_RELEASE} ]]; then
            return 0
        elif get_git_branch ${RELEASED_DIR}\
            | egrep -iq ${RELEASABLE_BRANCHES}; then
            return 0
        fi
    fi
    return 1
}

parse_cli "$@"
ret=0
if release_test; then
    log "Releasing ${RELEASABLE}"
    for img in ${RELEASABLE};do
        docker_registry=
        # registry
        image_pattern="\(\([^:]\+:[^/]\+\)\/\)\?"
        # repo
        image_pattern="${image_pattern}\(\(\([^\/:]\+\)\/\?\)"
        # image
        image_pattern="${image_pattern}\(\(\([^\/:]\+\)\/\?\)"
        # tag
        image_pattern="${image_pattern}:\?\(.*\)\)\)$"
        img_without_registry=$(echo "$img"|sed -e "s/$image_pattern/\3/g")
        docker_registry=$(echo "$img"|sed -e "s/$image_pattern/\2/g")
        vecho="";if [[ -n $FORCE_NO_RELEASE ]];then vecho="echo";fi
        if [[ -n $docker_registry ]];then
            log "docker login -> ${docker_registry}"
        else
            log "docker login"
        fi
        echo "$DOCKER_PASSWORD" | $vecho docker login --password-stdin \
            -u="$DOCKER_RELEASER" \
            $([[ -n ${docker_registry} ]] && echo "${docker_registry}")
        die_in_error "Login for $DOCKER_RELEASER failed on $docker_registry"
        ( if [[ -n "${docker_registry}" ]];then \
            output_in_error $vecho vv \
            docker push "${docker_registry}"/"${img_without_registry}";\
        else \
            output_in_error $vecho \
            vv docker push "${img_without_registry}";\
        fi
        )
        if [[ ${?} != 0 ]];then
            log "Failed to release: ${img}"
            ret=1
        else
            log "Released: ${img}"
        fi
    done
    log "release done"
else
    log "Release test failed, release skipped"
fi
die_in_error_ ${ret} "Release failed ($ret)"
# vim:set et sts=4 ts=4 tw=80:
