# For quickier rebuilds, we isolate each step of the installation
# and their requisites; together with docker cache

# __STRIPME__: __IMAGE__ will be replaced, see docker/docker_gen_dockerfiles.sh
FROM __IMAGE__
ENV container docker
ARG COPS_ROOT=__COPS_ROOT__
ENV COPS_ROOT $COPS_ROOT
ENV COPS_APPLY_ROLE "${COPS_ROOT}/bin/cops_apply_role -vvvv"

# 1/ - Prebuild requirements & helpers,
#    - Make also life easier for systemd based containers
COPY requirements/os_* \
     hacking/container_rootfs/sbin/cops_container_snapshot.sh \
     hacking/container_rootfs/sbin/cops_container_strip.sh \
     hacking/container_rootfs/sbin/cops_container_cleanup.sh \
     bin/cops_shell_common \
     bin/cops_pkgmgr_install.sh \
     bin/cops_reset_passwords.sh \
     /bootstrap/
RUN bash -c 'step_rev=2;\
    :;\
    silent() { SILENT=1 /bootstrap/cops_shell_common vv "${@}"; };\
    cd /bootstrap;\
    DISTRIB_ID=$(. cops_shell_common && echo $DISTRIB_ID);\
    if [ "x$DISTRIB_ID" = "x" ]; then exit 139;fi;\
    WANTED_PACKAGES="$(cat os_packages.${DISTRIB_ID} 2>/dev/null | xargs -n1)";\
    WANTED_DOCKER_PACKAGES="$(cat os_docker_packages.${DISTRIB_ID} 2>/dev/null | xargs -n1)";\
    WANTED_EXTRA_PACKAGES="$(cat os_extra_packages.${DISTRIB_ID} 2>/dev/null | xargs -n1)";\
    :;\
    if ((which which && which systemd) || \
         command -v systemd )>/dev/null 2>&1 \
       || [ -e /lib/systemd/systemd ];then \
      WANTED_PACKAGES="systemd ${WANTED_PACKAGES}";\
    fi;\
    :;\
    WANTED_PACKAGES="${WANTED_PACKAGES} ${WANTED_DOCKER_PACKAGES}";\
    export WANTED_PACKAGES WANTED_EXTRA_PACKAGES;\
    set -e;\
    echo "packages: " $WANTED_PACKAGES >&2;\
    echo "extras: "$WANTED_EXTRA_PACKAGES >&2;\
    DO_INSTALL=y DO_UPGRADE=y DO_UPDATE=y silent ./cops_pkgmgr_install.sh;\
    silent ./cops_container_cleanup.sh;\
    silent ./cops_container_snapshot.sh;'

# 2/ isolate virtualenv contruction
COPY requirements/os_* \
     requirements/python_* \
     ${COPS_ROOT}/requirements/
RUN bash -c 'step_rev=2;set -e;\
    silent() { SILENT=1 /bootstrap/cops_shell_common vv "${@}"; };\
    cd ${COPS_ROOT};\
    silent virtualenv --system-site-packages --unzip-setuptools venv;\
    . venv/bin/activate;\
    :;\
    silent pip install -U pip;\
    silent pip install -U -r requirements/python_requirements.txt;\
    :;\
    silent /bootstrap/cops_container_snapshot.sh;'

# 3/ Run install script to finish installation
# We remove a package (git) to test the system install routines
COPY .corpusops ${COPS_ROOT}/.corpusops
COPY bin ${COPS_ROOT}/bin
COPY src ${COPS_ROOT}/src
COPY setup.py ${COPS_ROOT}/setup.py
RUN bash -c 'step_rev=2;set -e;\
    silent() { SILENT=1 $COPS_ROOT/bin/cops_shell_common vv "${@}"; };\
    DISTRIB_ID=$(. /bootstrap/cops_shell_common && echo $DISTRIB_ID);\
    cd ${COPS_ROOT};\
    :;\
    if echo ${DISTRIB_ID} | egrep -iq "ubuntu|debian";then\
        silent apt-get remove -y --force-yes git;\
        silent apt-get update -qq;\
    fi;\
    :;\
    silent bin/install.sh -C --skip-sync-code;\
    :;\
    silent /bootstrap/cops_container_snapshot.sh;\
    rm -rf /bootstrap;'

# 4/ Bring in all playbooks & roles
COPY .git ${COPS_ROOT}/.git
COPY roles ${COPS_ROOT}/roles
COPY playbooks ${COPS_ROOT}/playbooks
RUN bash -c 'step_rev=3;set -e;\
    silent() { SILENT=1 $COPS_ROOT/bin/cops_shell_common vv "${@}"; };\
    cd $COPS_ROOT;\
    : be sure every file is in place;\
    silent git reset --hard HEAD;\
    : DISABLED, use only local checkout;\
    : bin/install.sh -C --only-sync-code;\
    silent hacking/container_rootfs/sbin/cops_container_snapshot.sh;'

# Now copy all rootfs helpers & make the container a good systemd / process
# manager citizen
RUN bash -c 'step_rev=3;set -e;\
    silent() { SILENT=1 $COPS_ROOT/bin/cops_shell_common vv "${@}"; };\
    silent $COPS_ROOT/hacking/sync_files ;\
    silent rsync -av $COPS_ROOT/hacking/container_rootfs/ /;\
    silent /sbin/cops_container_activate_core_services.sh;\
    silent /sbin/cops_container_cleanup.sh;\
    silent /sbin/cops_container_snapshot.sh;'

# pack any found git repo
RUN bash -c 'step_rev=3;set -e;\
    silent() { SILENT=1 $COPS_ROOT/bin/cops_shell_common vv "${@}"; };\
    /sbin/cops_container_strip.sh'
# vim:set et:
