#!/usr/bin/env bash
cd "$(dirname ${0})/.."
export LOGGER_NAME=$(basename $0)

sc=hacking/build_env
[[ ! -e $sc ]] && echo "missing $sc" >&2
. "$sc" || exit 1

usage () {
    NO_HEADER=y die '
Regenerate found distributions dockerfiles from template

 [NO_SYNC=] \
 [NO_BUILD=y] \
 [NO_ROLES_TEST=y]\
 [NO_NOT_IN_DOCKER_ROLES_TEST=y]\
 [ROLES_TO_TEST=]\
 [NOCOLOR=y] \
 [NO_GEN=y] \
 [DEBUG=y] \
 [IMAGES=xxx] \
    '"$0"'
'
}

parse_cli() {
    parse_cli_common "${@}"
}

parse_cli "$@"

if [[ -n "${NO_SYNC}" ]];then
    log "Skipping code sync"
else
    vv bin/install.sh -C --synchronize-code
    die_in_error "SYNC failed"
fi

if [[ -n "${NO_BUILD}" ]];then
    log "Skipping build step"
else
    vv hacking/build_images
    die_in_error "BUILD failed"
fi

if [[ -n "${NO_ROLES_TEST}" ]];then
    log "Skipping roles test step"
else
    roles_to_test="${ROLES_TO_TEST-}"
    if [[ -z ${roles_to_test} ]];then
        roles_to_test="$(get_short_roles_to_test \
            "$roles_to_test" "${BASE_ROLES}")"
        roles_to_test="$(get_short_roles_to_test \
            "$roles_to_test" "${CONFIG_ROLES}")"
        roles_to_test="$(get_short_roles_to_test \
            "$roles_to_test" "${SERVICES_ROLES}")"
        if echo $image | egrep -iq "debian|ubuntu"; then
            roles_to_test="$(get_short_roles_to_test \
                "$roles_to_test" ${DEBIAN_ROLES})"
        fi
        if echo $image | egrep -iq "ubuntu"; then
            roles_to_test="$(get_short_roles_to_test \
                "$roles_to_test" ${UBUNTU_ROLES})"
        fi
    fi
    roles_to_test="$(get_roles_to_test $roles_to_test)"
    vv hacking/test_roles "${roles_to_test}"
    die_in_error "roles tests failed"
fi
if [[ -n "${NO_NOT_IN_DOCKER_ROLES_TEST}" ]];then
    log "Skipping not in docker roles test step"
else
    ret=0
    if [[ -n $TRAVIS ]]; then NOT_IN_DOCKER_ROLES=;fi
    nid_roles_to_test="$(get_short_roles_to_test \
        "$nid_roles_to_test" ${NOT_IN_DOCKER_ROLES})"
    if [[ -n "e$NOT_IN_DOCKER_ROLES" ]] && ! NOT_IN_DOCKER=1 vv \
        hacking/test_roles "$nid_roles_to_test"; then
        ret=1
    fi
    die_in_error_ "${ret}" "roles tests failed"
fi
# vim:set et sts=4 ts=4 tw=80:
