---
sudo: required
dist: trusty
env:
  matrix:
    - DISTRIBS="ubuntu:16.04"
language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
install:
  - bin/install.sh -C -S -b "$(git log HEAD|head -n1|awk '{print $2}')"
script:
  - hacking/test_script
after_success:
  - hacking/docker_travis_release
