---
sudo: required
dist: trusty
env:
  matrix:
    - IMAGES="ubuntu:16.04"
    - IMAGES="ubuntu:14.04"
    - IMAGES="ubuntu:latest"
language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
install:
  - bin/install.sh -C -S -b "$(git log HEAD|head -n1|awk '{print $2}')"
script:
  - hacking/test_script
after_success:
  - DEBUG=1 hacking/docker_release
