---
sudo: required
dist: trusty
env:
  matrix:
    - IMAGES="ubuntu:16.04"
    - IMAGES="ubuntu:14.04"
    - IMAGES="ubuntu:latest"
language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
install:
  - |
    if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]];then
        CORPUSOPS_BRANCH="$(git log HEAD|head -n1|awk '{print $2}')"
        debug "Is a travis pull request, use changeset: ${changeset}"
    else
        CORPUSOPS_BRANCH="${TRAVIS_BRANCH}"
    fi
    export CORPUSOPS_BRANCH
    bin/install.sh -C -S
script:
  - |
    if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]];then
        CORPUSOPS_BRANCH="$(git log HEAD|head -n1|awk '{print $2}')"
        debug "Is a travis pull request, use changeset: ${changeset}"
    else
        CORPUSOPS_BRANCH="${TRAVIS_BRANCH}"
    fi
    export CORPUSOPS_BRANCH
    hacking/test_script
after_success:
  - DEBUG=1 hacking/docker_release
