# For quickier rebuilds, we isolate each step of the installation
# and their requisites; together with docker cache

FROM corpusops/centos:7_preprovision
ENV container docker
ARG COPS_ROOT=/srv/corpusops/corpusops.bootstrap

# 5/ Make the docker image a preconfigured-for-production image
RUN step_rev=1;set -ex;\
    crole="${COPS_ROOT}/bin/cops_apply_role -vvvv";\
    $crole "${COPS_ROOT}/playbooks/corpusops/provision/server.yml";\
    /sbin/cops_container_cleanup.sh;\
    /sbin/cops_container_snapshot.sh;

# pack any found git repo
RUN step_rev=1;set -ex;${COPS_ROOT}/bin/git_pack /;\
    /sbin/cops_container_cleanup.sh;\
    /sbin/cops_container_snapshot.sh;
# vim:set et:
