# For quickier rebuilds, we isolate each step of the installation
# and their requisites; together with docker cache

FROM corpusops/ubuntu:16.04_preprovision
ENV container docker
ARG COPS_ROOT=/srv/corpusops/corpusops.bootstrap

# 5/ Make the docker image a preconfigured-for-production image
RUN bash -c 'step_rev=2;set -e;\
    silent() { SILENT=1 $COPS_ROOT/bin/cops_shell_common vv "${@}"; };\
    crole="${COPS_ROOT}/bin/cops_apply_role -vvvv";\
    silent $crole "${COPS_ROOT}/playbooks/corpusops/provision/server.yml";\
    silent /sbin/cops_container_cleanup.sh;\
    silent /sbin/cops_container_snapshot.sh;'

# pack any found git repo
RUN bash -c 'step_rev=2;set -e;\
    silent() { SILENT=1 $COPS_ROOT/bin/cops_shell_common vv "${@}"; };\
    silent ${COPS_ROOT}/bin/git_pack /;\
    silent /sbin/cops_container_cleanup.sh;\
    silent /sbin/cops_container_snapshot.sh;'
# vim:set et:
