# For quickier rebuilds, we isolate each step of the installation
# and their requisites; together with docker cache

FROM corpusops/ubuntu:16.04_preprovision

# 5/ Make the docker image a preconfigured-for-production image
RUN bash -c 'step_rev=2;set -e;\
    silent() { SILENT=1 $COPS_ROOT/bin/cops_shell_common vv "${@}"; };\
    silent $COPS_APPLY_ROLE "${COPS_ROOT}/playbooks/corpusops/provision/server.yml"'

# pack any found git repo
RUN bash -c 'step_rev=3;set -e;\
    silent() { SILENT=1 $COPS_ROOT/bin/cops_shell_common vv "${@}"; };\
    /sbin/cops_container_strip.sh'
# vim:set et:
