#!/usr/bin/env bash
COPS_VAGRANT_DIR=${COPS_VAGRANT_DIR:-$(readlink -f $(dirname "$(readlink -f "$0")/.."))}
. "$COPS_VAGRANT_DIR/common.sh" || exit 1
cd "$W"

usage () {
    NO_HEADER=y die '
Provision a vagrant vm

[NO_CLEANUP=] \
[NO_APT_CLEANUP=] \
    '"$0"'
'
}


parse_cli() {
    parse_cli_common "${@}"
}


cleanup () {
    if [[ -n $NO_CLEANUP ]];then
        log "NO_CLEANUP set, skip cleanup"
        return 0
    fi
    # rm this cron on vbox
    rm -vf /etc/cron.daily/mlocate
    if [[ -z $NO_APT_CLEANUP ]];then
        rm -vf /var/cache/apt/archives/*deb
        rm -rf  /var/lib/apt/lists/*
    fi
}


parse_cli "$@"
play_ansible_playbooks
cleanup
# vim:set et sts=4 ts=4 tw=80:
