#!/usr/bin/env bash
COPS_VAGRANT_DIR=${COPS_VAGRANT_DIR:-$(readlink -f $(dirname "$(readlink -f "$0")/.."))}
. "$COPS_VAGRANT_DIR/common.sh" || exit 1
cd "$W"

usage () {
    NO_HEADER=y die '
Provision a vagrant vm

[NO_CLEANUP=] \
[NO_APT_CLEANUP=] \
    '"$0"'
'
}


parse_cli() {
    parse_cli_common "${@}"
}

extra() {
    #### extra image stuff
    /srv/rancher/rancherserver/cleanup.sh
}


parse_cli "$@"
extra
# vim:set et sts=4 ts=4 tw=80:
