#!/usr/bin/env bash
COPS_VAGRANT_DIR=${COPS_VAGRANT_DIR:-$(readlink -f $(dirname "$(readlink -f "$0")/.."))}
. "$COPS_VAGRANT_DIR/common.sh" || exit 1
cd "$W"

usage () {
    NO_HEADER=y die '
Provision a vagrant vm

[NO_MOTD=] \
    '"$0"'
'
}


motd() {
    if [[ -n $NO_MOTD ]];then
        log "NO_CLEANUP set, skip cleanup"
        return 0
    fi
    warn "Provision is finished"
    log "  Machine NUM: $COPS_MACHINE_NUM"
    log "  Machine IP: $COPS_PRIVATE_IP"
    log "  Machine Private network: $COPS_PRIVATE_NETWORK"
    log "  Machine hostname: $COPS_HOSTNAME"
    log "  Machine domain: $COPS_DOMAIN"
}


parse_cli "$@"
motd
# vim:set et sts=4 ts=4 tw=80:
