---
- hosts: all
  vars:
    ansible_become_user: root
  tasks:
    - include_tasks: "./tasks/load_vars.yml"
    - shell: sshfs --version
      register: has_sshfs_test
      failed_when: false
      changed_when: false
    - include_tasks: "./tasks/install_sshfs.yml"
      when: |
        ((not vbox_cops.get('SKIP_INSTALL_SSHFS', False) and
         (has_sshfs_test.rc!=0)) or
         vbox_cops.get('FORCE_INSTALL_SSHFS', False))

