#!/usr/bin/env bash
# BEGIN: corpusops common glue
# scripts vars
SCRIPT=$0
LOGGER_NAME=${LOGGER_NAME-$(basename $0)}
SCRIPT_NAME=$(basename "${SCRIPT}")
SCRIPT_DIR=$(cd "$(dirname $0)" && pwd)
SCRIPT_ROOT=${SCRIPT_ROOT:-$(dirname $SCRIPT_DIR)}
# OW: from where script was called (must be defined from callee)
OW="${OW:-$(pwd)}"
# W is script_dir/..
W=${OVERRIDEN_W:-$(cd "$SCRIPT_DIR/.." && pwd)}
#
#
DEFAULT_COPS_ROOT="/srv/corpusops/corpusops.bootstrap"
DEFAULT_COPS_URL="https://github.com/corpusops/corpusops.bootstrap"
#
SYSTEM_COPS_ROOT=${SYSTEM_COPS_ROOT-$DEFAULT_COPS_ROOT}
DOCKER_COPS_ROOT=${DOCKER_COPS_ROOT-$SYSTEM_COPS_ROOT}
COPS_URL=${COPS_URL-$DEFAULT_COPS_URL}
BASE_PREPROVISION_IMAGES="ubuntu:latest_preprovision"
BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/ubuntu:16.04_preprovision"
BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/ubuntu:14.04_preprovision"
BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/centos:7_preprovision"
BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:latest"

BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:latest"
BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:16.04"
BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:14.04"
BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/centos:7"
BASE_IMAGES="$BASE_PREPROVISION_IMAGES $BASE_CORE_IMAGES"
EXP_PREPROVISION_IMAGES=""
EXP_PREPROVISION_IMAGES="$EXP_PREPROVISION_IMAGES archlinux:latest_preprovision"
EXP_PREPROVISION_IMAGES="$EXP_PREPROVISION_IMAGES debian:latest_preprovision"
EXP_PREPROVISION_IMAGES="$EXP_PREPROVISION_IMAGES debian:stretch_preprovision"
EXP_PREPROVISION_IMAGES="$EXP_PREPROVISION_IMAGES debian:jessie_preprovision"
EXP_CORE_IMAGES=""
EXP_CORE_IMAGES="$EXP_CORE_IMAGES corpusops/archlinux:latest"
EXP_CORE_IMAGES="$EXP_CORE_IMAGES corpusops/debian:latest"
EXP_CORE_IMAGES="$EXP_CORE_IMAGES corpusops/debian:stretch"
EXP_CORE_IMAGES="$EXP_CORE_IMAGES corpusops/debian:jessie"
EXP_IMAGES="$EXP_PREPROVISION_IMAGES $EXP_CORE_IMAGES"
#
# colors
RED="\\e[0;31m"
CYAN="\\e[0;36m"
YELLOW="\\e[0;33m"
NORMAL="\\e[0;0m"
NO_COLOR=${NO_COLORS-${NO_COLORS-${NOCOLOR-${NOCOLORS-}}}}
LOGGER_NAME=${LOGGER_NAME:-corpusops_build}
ERROR_MSG="There were errors"
do_trap_() { rc=$?;func=$1;sig=$2;${func};if [ "x${sig}" != "xEXIT" ];then kill -${sig} $$;fi;exit $rc; }
do_trap() { rc=${?};func=${1};shift;sigs=${@};for sig in ${sigs};do trap "do_trap_ ${func} ${sig}" "${sig}";done; }
is_ci() {
    return $( ( [[ -n ${TRAVIS-} ]] || [[ -n ${GITLAB_CI} ]] );echo $?;)
}
log_() {
    reset_colors;msg_color=${2:-${YELLOW}};
    logger_color=${1:-${RED}};
    logger_slug="${logger_color}[${LOGGER_NAME}]${NORMAL} ";
    shift;shift;
    if [[ -n ${NO_LOGGER_SLUG} ]];then logger_slug="";fi
    printf "${logger_slug}${msg_color}$(echo "${@}")${NORMAL}\n" >&2;
    printf "" >&2;  # flush
}
reset_colors() { if [[ -n ${NO_COLOR} ]];then BLUE="";YELLOW="";RED="";CYAN="";fi; }
log() { log_ "${RED}" "${CYAN}" "${@}"; }
get_chrono() { date "+%F_%H-%M-%S"; }
cronolog() { log_ "${RED}" "${CYAN}" "($(get_chrono)) ${@}"; }
debug() { if [[ -n "${DEBUG// }" ]];then log_ "${YELLOW}" "${YELLOW}" "${@}"; fi; }
warn() { log_ "${RED}" "${CYAN}" "${YELLOW}[WARN] ${@}${NORMAL}"; }
bs_log(){ log_ "${RED}" "${YELLOW}" "${@}"; }
bs_yellow_log(){ log_ "${YELLOW}" "${YELLOW}" "${@}"; }
may_die() {
    reset_colors
    thetest=${1:-1}
    rc=${2:-1}
    shift
    shift
    if [ "x${thetest}" != "x0" ]; then
        if [[ -z "${NO_HEADER-}" ]]; then
            NO_LOGGER_SLUG=y log_ "" "${CYAN}" "Problem detected:"
        fi
        NO_LOGGER_SLUG=y log_ "${RED}" "${RED}" "$@"
        exit $rc
    fi
}
die() { may_die 1 1 "${@}"; }
die_in_error_() {
    ret=${1}; shift; msg="${@:-"$ERROR_MSG"}";may_die "${ret}" "${ret}" "${msg}";
}
die_in_error() { die_in_error_ "${?}" "${@}"; }
die_() { NO_HEADER=y die_in_error_ $@; }
sdie() { NO_HEADER=y die $@; }
parse_cli() { parse_cli_common "${@}"; }
parse_cli_common() {
    USAGE=
    for i in ${@-};do
        case ${i} in
            --no-color|--no-colors|--nocolor|--no-colors)
                NO_COLOR=1;;
            -h|--help)
                USAGE=1;;
            *) :;;
        esac
    done
    reset_colors
    if [[ -n ${USAGE} ]]; then
        usage
    fi
}
has_command() {
    ret=1
    if which which >/dev/null 2>/dev/null;then
      if which "${@}" >/dev/null 2>/dev/null;then
        ret=0
      fi
    else
      if command -v "${@}" >/dev/null 2>/dev/null;then
        ret=0
      else
        if hash -r "${@}" >/dev/null 2>/dev/null;then
            ret=0
        fi
      fi
    fi
    return ${ret}
}
pipe_return() {
    local filter=$1;shift;local command=$@;
    (((($command; echo $? >&3) | $filter >&4) 3>&1) | (read xs; exit $xs)) 4>&1;
}
output_in_error() { ( do_trap output_in_error_post EXIT TERM QUIT INT;\
                      output_in_error_ "${@}" ; ); }
output_in_error_(){
    if [[ -n ${OUTPUT_IN_ERROR_DEBUG-} ]];then set -x;fi
    if is_ci;then
        DEFAULT_CI_BUILD=y
    fi
    CI_BUILD="${CI_BUILD-${DEFAULT_CI_BUILD-}}"
    if [[ -n $CI_BUILD ]];then
        DEFAULT_NO_OUTPUT=y
        DEFAULT_DO_OUTPUT_TIMER=y
    fi
    VERBOSE="${VERBOSE-}"
    TIMER_FREQUENCE="${TIMER_FREQUENCE:-120}"
    NO_OUTPUT="${NO_OUTPUT-${DEFAULT_NO_OUTPUT-1}}"
    DO_OUTPUT_TIMER="${DO_OUTPUT_TIMER-$DEFAULT_DO_OUTPUT_TIMER}"
    LOG=${LOG-}
    if [[ -n $NO_OUTPUT ]];then
        if [[ -z "${LOG}" ]];then
            LOG=$(mktemp)
            DEFAULT_CLEANUP_LOG=y
        else
            DEFAULT_CLEANUP_LOG=
        fi
    else
        DEFAULT_CLEANUP_LOG=
    fi
    CLEANUP_LOG=${CLEANUP_LOG:-${DEFAULT_CLEANUP_LOG}}
    if [[ -n $VERBOSE ]];then
        log "Running$([[ -n $LOG ]] && echo "($LOG)"; ): $@";
    fi
    TMPTIMER=
    if [[ -n ${DO_OUTPUT_TIMER} ]]; then
        TMPTIMER=$(mktemp)
        ( i=0;\
          while test -f $TMPTIMER;do\
           i=$((++i));\
           if [ `expr $i % $TIMER_FREQUENCE` -eq 0 ];then \
               log "BuildInProgress$([[ -n $LOG ]] && echo "($LOG)"; ): ${@}";\
             i=0;\
           fi;\
           sleep 1;\
          done;\
          if [[ -n $VERBOSE ]];then log "done: ${@}";fi; ) &
    fi
    if [[ -n $NO_OUTPUT ]];then
        "${@}" >>"$LOG" 2>&1;ret=$?
    else
        if [[ -n $LOG ]] && has_command tee;then
            pipe_return "tee -a $LOG" "${@}";ret=$?
        else
            "${@}";ret=$?
        fi
    fi
    if [[ -e "$TMPTIMER" ]]; then rm -f "${TMPTIMER}";fi
    if [[ -z ${OUTPUT_IN_ERROR_NO_WAIT-} ]];then wait;fi
    if [ -e "$LOG" ] &&  [[ "${ret}" != "0" ]] && [[ -n $NO_OUTPUT ]];then
        cat "$LOG" >&2
    fi
    if [[ -n ${OUTPUT_IN_ERROR_DEBUG-} ]];then set +x;fi
    return ${ret}
}
output_in_error_post() {
    if [[ -e "$TMPTIMER" ]]; then rm -f "${TMPTIMER}";fi
    if [[ -e "$LOG" ]] && [[ -n $CLEANUP_LOG ]];then rm -f "$LOG";fi
}
test_silent_log() { ( [[ -z ${NO_SILENT-} ]] && ( [[ -n ${SILENT_LOG-} ]] || [[ -n "${SILENT_DEBUG}" ]] ) ); }
test_silent() { ( [[ -z ${NO_SILENT-} ]] && ( [[ -n ${SILENT-} ]] || test_silent_log ) ); }
silent_run_() {
    (LOG=${SILENT_LOG:-${LOG}};
     NO_OUTPUT=${NO_OUTPUT-};\
     if test_silent;then NO_OUTPUT=y;fi;output_in_error "$@";)
}
silent_run() { ( silent_run_ "${@}" ; ); }
run_silent() {
    (
    DEFAULT_RUN_SILENT=1;
    if [[ -n ${NO_SILENT-} ]];then DEFAULT_RUN_SILENT=;fi;
    SILENT=${SILENT-DEFAULT_RUN_SILENT} silent_run "${@}";
    )
}
vvv() { debug "${@}";silent_run "${@}"; }
vv() { log "${@}";silent_run "${@}"; }
silent_vv() { SILENT=${SILENT-1} vv "${@}"; }
quiet_vv() { if [[ -z ${QUIET-} ]];then log "${@}";fi;run_silent "${@}";}
version_lte() { [  "$1" = "$(printf "$1\n$2" | sort -V | head -n1)" ]; }
version_lt() { [ "$1" = "$2" ] && return 1 || version_lte $1 $2; }
version_gte() { [  "$2" = "$(printf "$1\n$2" | sort -V | head -n1)" ]; }
version_gt() { [ "$1" = "$2" ] && return 1 || version_gte $1 $2; }
is_archlinux_like() { echo $DISTRIB_ID | egrep -iq "archlinux|arch"; }
is_debian_like() { echo $DISTRIB_ID | egrep -iq "debian|ubuntu|mint"; }
is_redhat_like() { echo $DISTRIB_ID \
        | egrep -iq "((^ol$)|rhel|redhat|red-hat|centos|fedora)"; }
set_lang() { locale=${1:-C};export LANG=${locale};export LC_ALL=${locale}; }
detect_os() {
    # this function should be copiable in other scripts, dont use adjacent functions
    UNAME="${UNAME:-"$(uname | awk '{print tolower($1)}')"}"
    PATH="${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
    SED="sed"
    if [ "x${UNAME}" != "xlinux" ] && hash -r gsed >/dev/null 2>&1; then
        SED=gsed
    fi
    DISTRIB_CODENAME=""
    DISTRIB_ID=""
    DISTRIB_RELEASE=""
    if hash -r lsb_release >/dev/null 2>&1; then
        DISTRIB_ID=$(lsb_release -si)
        DISTRIB_CODENAME=$(lsb_release -sc)
        DISTRIB_RELEASE=$(lsb_release -sr)
    elif [ -e /etc/lsb-release ];then
        debug "No lsb_release, sourcing manually /etc/lsb-release"
        DISTRIB_ID=$(. /etc/lsb-release;echo ${DISTRIB_ID})
        DISTRIB_CODENAME=$(. /etc/lsb-release;echo ${DISTRIB_CODENAME})
        DISTRIB_RELEASE=$(. /etc/lsb-release;echo ${DISTRIB_RELEASE})
    elif [ -e /etc/os-release ];then
        DISTRIB_ID=$(. /etc/os-release;echo $ID)
        DISTRIB_CODENAME=$(. /etc/os-release;echo $VERSION)
        DISTRIB_CODENAME=$(echo $DISTRIB_CODENAME |sed -e "s/.*(\([^)]\+\))/\1/")
        DISTRIB_RELEASE=$(. /etc/os-release;echo $VERSION_ID)
    elif [ -e /etc/redhat-release ];then
        RHRELEASE=$(cat /etc/redhat-release)
        DISTRIB_CODENAME=${RHRELEASE}
        DISTRIB_RELEASE=${RHRELEASE}
        DISTRIB_ID=${RHRELEASE}
        DISTRIB_CODENAME=$(echo $DISTRIB_CODENAME |sed -e "s/.*(\([^)]\+\))/\1/")
        DISTRIB_RELEASE=$(echo $DISTRIB_RELEASE |sed -e "s/release \([0-9]\)/\1/")
        DISTRIB_ID=$(echo $DISTRIB_ID | awk '{print tolower($1)}')
    else
        if ! ( echo ${@-} | grep -q no_fail );then
            echo "unexpected case, no lsb_release" >&2
            exit 1
        fi
    fi
    export DISTRIB_ID DISTRIB_CODENAME DISTRIB_RELEASE
}
get_command() {
    local p=
    local cmd="${@}"
    if which which >/dev/null 2>/dev/null;then
        p=$(which "${cmd}" 2>/dev/null)
    fi
    if [ "x${p}" = "x" ];then
        p=$(export IFS=:;
            echo "${PATH-}" | while read -ra pathea;do
                for pathe in "${pathea[@]}";do
                    pc="${pathe}/${cmd}";
                    if [ -x "${pc}" ]; then
                        p="${pc}"
                    fi
                done
                if [ "x${p}" != "x" ]; then echo "${p}";break;fi
            done )
    fi
    if [ "x${p}" != "x" ];then
        echo "${p}"
    fi
}
cleanup_docker_tag() { echo "${@}"|sed -re "s/\.|[-_]//g"|awk '{print tolower($0)}'; }
get_container_id() { local n=${1};local cid=$(docker ps -q -a --filter 'name='$n); echo "${cid}"; }
sane_container_name() { local n=${1};n=${n//:/};n=${n//_/};n=${n//-/};n=${n//\//};n=${n//\./};echo $n; }
get_images() { docker images --no-trunc -q "${@}" 2>/dev/null|awk '!seen[$0]++'; }
get_image() { get_images "${@}" | head -n 1; }
get_docker_ids() { docker inspect -f '{{.Id}}' "${@}" 2>/dev/null; }
save_container() {
    local n="${1}"
    local d="${2:-${n}}"
    local running=$(docker ps -q    --filter 'name='$n)
    if [[ -n "${running}" ]];then
        vv docker kill "${running}"
    fi
    local cid=$(get_container_id $n)
    if [[ -n "${cid}" ]];then
        vv docker commit "$cid" "$d"
        vv docker rm "$cid"
    else
        img=${initial_img}
    fi
}
get_git_changeset() { ( cd "${1:-$(pwd)}" && git log HEAD|head -n1|awk '{print $2}'); }
get_git_branch() {
   ( cd "${1:-$(pwd)}" &&\
     git rev-parse --abbrev-ref HEAD | grep -v HEAD || \
     git describe --exact-match HEAD 2> /dev/null || \
     git rev-parse HEAD)
}
get_git_branchs() { ( cd "${1:-$(pwd)}" && git branch|sed -e "s/^\*\? \+//g"); }
get_full_chrono() { date "+%F_%H-%M-%S-%N"; }
get_random_slug() { len=${1:-32};strings=${2:-'a-zA-Z0-9'};echo "$(cat /dev/urandom|tr -dc "$strings"|fold -w ${len}|head -n 1)"; }
may_sudo() {
    if [ "$(whoami)" != "root" ] && [ -z "${NO_SUDO-}" ];then
        echo "sudo $([[ -z $DIRECT_SUDO ]] && echo "-HE")"
    fi
}
get_ancestor_from_dockerfile() {
    local dockerfile=${1}
    local ancestor=
    if [[ -e "${dockerfile}" ]] && egrep -q ^FROM "${dockerfile}"; then
        ancestor=$(egrep ^FROM "${dockerfile}"\
            | head -n1 | awk '{print $2}' | xargs -n1| sort -u )
    fi
    echo ${ancestor}
}
do_tmp_cleanup() {
    local tmp_dockers=$2
    local tmp_files=$1
    local tmp_imgs=$3
    log "Post cleanup"
    for tmp_file in ${tmp_files};do
        if [ -e "${tmp_file}" ]; then
            vv rm -f "${tmp_file}"
        fi
    done
    for test_docker in ${tmp_dockers};do
        test_dockerid=$(vvv get_container_id ${test_docker})
        if [[ "${test_dockerid}" != "" ]]; then
            log "Removing produced test docker ${test_docker}"
            docker rm -f "${test_dockerid}"
        fi
    done
    for test_tag in ${tmp_imgs};do
        test_tagid=$(vvv get_image ${test_tag})
        if [[ "${test_tagid}" != "" ]]; then
            log "Removing produced test image: ${test_tag}"
            docker rmi "${test_tagid}"
        fi
    done
}
update_wd_to_br() {
    (
        local wd="${2:-$(pwd)}"
        local up_branch="${1}"
        cd "${wd}" || die "${wd} does not exists"
        if ! git diff --exit-code -q;then
            git stash
        fi &&\
        vv git pull origin "${up_branch}"
    )

}
upgrade_wd_to_br() {
    (
        local wd="${2:-$(pwd)}"
        local up_branch="${1}"
        cd "${wd}" || die "${wd} does not exists"
        local test_branch="${3:-$(get_git_branch)}"
        local existing_gitmodules="$(git submodule status|awk '{print $2}')"
        if [ "x${test_branch}" != "x${up_branch}" ];then
            warn "Upgrading $wd to branch: $up_branch"
            git fetch --all || die "git fetch in $wd failed"
            if get_git_branchs | egrep -q "^${up_branch}$";then
                vv git checkout ${up_branch} &&\
                    vv git reset --hard origin/${up_branch}
            else
                vv git checkout origin/${up_branch} -b ${up_branch}
            fi
        fi
        update_wd_to_br "$up_branch" "$wd" &&\
        while read subdir;do
            subdir=$(echo $subdir|sed -e "s/^\.\///g")
            if [ -h "${subdir}/.git" ] || [ -f "${subdir}/.git" ];then
                debug "Checking if ${subdir} is always a submodule"
                if [ -e .gitmodules ] && ( grep -q -- "${subdir}" .gitmodules );then
                    debug "${subdir} is always a gitmodule"
                else
                    warn "${subdir} is not a git submodule anymore"
                    vv rm -rf "${subdir}"
                fi
            fi
        done < <( echo "${existing_gitmodules}" )
        if [ -e .gitmodules ];then
            warn "Upgrading submodules in $wd"
            vv git submodule update --recursive
        fi
    )
}
get_python2() {
    local py2=
    for i in python2.7 python2.6 python-2.7 python-2.6 python-2;do
        local lpy=$(get_command $i 2>/dev/null)
        if [[ -n $lpy ]] && ( ${lpy} -V 2>&1| egrep -qi 'python 2' );then
            py2=${lpy}
            break
        fi
    done
    echo $py2
}
make_virtualenv() {
    local py=${1:-$(get_python2)}
    local DEFAULT_VENV_PATH=$SCRIPT_ROOT/venv
    local venv_path=${2-${VENV_PATH:-$DEFAULT_VENV_PATH}}
    local venv=$(get_command $(basename ${VIRTUALENV_BIN:-virtualenv}))
    local PIP_CACHE=${PIP_CACHE:-${venv_path}/cache}
    if [ "x${DEFAULT_VENV_PATH}" != "${venv_path}" ];then
        if [ ! -e "${venv_path}" ];then
            mkdir -p "${venv_path}"
        fi
        if [ -e "${DEFAULT_VENV_PATH}" ] && \
            [ "$DEFAULT_VENV_PATH" != "$venv_path" ] &&\
            [ ! -h "${DEFAULT_VENV_PATH}" ];then
            die "$DEFAULT_VENV_PATH is not a symlink but we want to create it"
        fi
        if [ -h $DEFAULT_VENV_PATH ] &&\
            [ "x$(readlink $DEFAULT_VENV_PATH)" != "$venv_path" ];then
            rm -f "${DEFAULT_VENV_PATH}"
        fi
        if [ ! -e $DEFAULT_VENV_PATH ];then
            ln -s "${venv_path}" "${DEFAULT_VENV_PATH}"
        fi
    fi
    if     [ ! -e "${venv_path}/bin/activate" ] \
        || [ ! -e "${venv_path}/lib" ] \
        || [ ! -e "${venv_path}/include" ] \
        ; then
        bs_log "Creating virtualenv in ${venv_path}"
        if [ ! -e "${PIP_CACHE}" ]; then
            mkdir -p "${PIP_CACHE}"
        fi
        if [ ! -e "${venv_path}" ]; then
            mkdir -p "${venv_path}"
        fi
    $venv \
        $( [[ -n $py ]] && echo "--python=$py"; ) \
        --system-site-packages --unzip-setuptools \
        "${venv_path}" &&\
    ( . "${venv_path}/bin/activate" &&\
      "${venv_path}/bin/easy_install" -U setuptools &&\
      "${venv_path}/bin/pip" install -U pip &&\
      deactivate; )
    fi
}
ensure_last_python_requirement() {
    local PIP=${PIP:-pip}
    local COPS_PYTHON=${COPS_PYTHON:-python}
    local i=
    local PIP_CACHE=${PIP_CACHE:-${VENV_PATH:-$(pwd)}/cache}
    # inside the for loop as at first pip can not have the opts
    # but can be upgraded to have them after
    local copt=
    if "$py" "$PIP" --help | grep -q download-cache; then
        copt="--download-cache"
    elif $PIP --help | grep -q cache-dir; then
        copt="--cache-dir"
    fi
    log "Installing last version of $@"
    if [[ -n "$copt" ]];then
        vvv "$COPS_PYTHON" "$PIP" install \
            --src "$(get_eggs_src_dir)" -U $copt "${PIP_CACHE}" $@
    else
        vvv "$COPS_PYTHON" "$PIP" install \
            --src "$(get_eggs_src_dir)" -U $@
    fi
}
usage() { die 128 "No usage found"; }
# END: corpusops common glue

COPS_ENV="
REUSE_ENV
SKIP_COPS_INSTALL
SKIP_COPS_SETUP
SKIP_COPS_UPDATE
SKIP_PRINT_ENV
SKIP_SET_CORE_VARIABLES
SKIP_COPS_FROM_SYSTEM
SKIP_COPS_CHECKOUT
NO_SHARED_COPS
NO_A_ARGS
NO_DEFAULT_VAULTS
NONINTERACTIVE
NO_SILENT
A_AP
A_BIN
A_CALLED_BIN
A_CRYPTED_VAULTS
A_CUSTOM_ARGS
A_DRY_RUN
A_GIT_NAMESPACE
A_GIT_PROJECT
A_GIT_SERVER
A_GIT_URL
A_INVENTORY_FILE
A_LAUNCH_CMD
A_USE_ANSIBLE
A_VAULT_NAME
A_VERBOSITY
COPS_CWD
COPS_SCRIPTS_DIR
COPS_INSTALLER
COPS_LOCAL_FOLDER
COPS_PLAYBOOKS
COPS_ROOT
COREVARS_VAULT
COPS_SILENTRUN
COPS_SCRIPTS_DIR
COPS_INSTALL_ARGS
COPS_UPDATE_ARGS
COPS_URL
LOCAL_COPS_ROOT
PLAYBOOK
PLAYBOOK_POST_ARGS
PLAYBOOK_POST_CUSTOM_ARGS
PLAYBOOK_PRE_ARGS
PLAYBOOK_PRE_CUSTOM_ARGS
SECRET_VAULT_PREFIX
SECRET_VAULTS
SYS_COPS_ROOT
VAULT_PASSWORD_VARIABLES_PREFIX
"


ensure_ansible_env() {
    if [[ -z "$A_ENV_NAME" ]];then
        die "Set ansible environment to use: \$A_ENV_NAME !"
    fi
}
print_env() {
    if [[ -z "${SKIP_PRINT_ENV-}" ]];then
        for i in $COPS_ENV;do
            eval "debug \$(echo $i=\$$i)"
        done
    fi
}
do_unset() {
    # those are not considered to be unset once define
    if [[ -z "${REUSE_ENV:-1}" ]];then
        debug "-> Clearing env"
		for i in $COPS_ENV;do
			eval "unset $i"
		done
    fi
}
set_core_variables() {
    if [[ -n "${SKIP_SET_CORE_VARIABLES-}" ]];then
        die_ 0 "\$SKIP_SET_CORE_VARIABLES set, skip generating $COREVARS_VAULT"
    fi

    if [ ! -e local ];then mkdir local;fi

    cat > "$COREVARS_VAULT" << EOF
---
cops_path: "$LOCAL_COPS_ROOT"
cops_cwd: "$COPS_CWD"
cops_playbooks: "$COPS_PLAYBOOKS"
EOF

    log "-> Using core vault: $COREVARS_VAULT"

    debug "$(cat $COREVARS_VAULT)"
}
set_vaultpwfiles() {
    vaultpwfiles=''
    debug "SECRET_VAULTS: $SECRET_VAULTS"
    for SECRET_VAULT in $SECRET_VAULTS;do
        vault=$(echo "$SECRET_VAULT"|awk -F@ '{print $1}')
        debug "Testing $vault"
        if [ -e $vault ];then
            log "-> Using secret vault: $vault"
            if "$A_AP" --help 2>&1|grep -q vault-id;then
                vaultpwfiles="--vault-id=$vault"
            else
                vaultpwfiles="--vault-password-file=$vault"
            fi
        else
            debug "No vault password found in $vault"
        fi
    done
    debug "vaultpwfiles: $vaultpwfiles"
}
set_base_vars() {
    A_ENV_NAME=${A_ENV_NAME-}
    if ( echo "$@" | egrep -iq vagrant; );then
        A_ENV_NAME=vagrant
    fi
    export A_ENV_NAME
    export COPS_CWD="${COPS_CWD:-${cops_cwd:-$(pwd)}}"
    export COPS_SCRIPTS_DIR="${COPS_SCRIPTS_DIR:-$COPS_CWD/.ansible/scripts}"
    export COPS_LOCAL_FOLDER="${COPS_LOCAL_FOLDER:-$COPS_CWD/local}"
    export REUSE_ENV="${REUSE_ENV-}"
}
call_cops_installer() { output_in_error "$COPS_INSTALLER" $@; }
#
set_base_vars $@
do_unset
#
if [ -f "$COPS_SCRIPTS_DIR/ansible_deploy_env.local" ];then
    . "$COPS_SCRIPTS_DIR/ansible_deploy_env.local"
fi
#
set_base_vars $@
log "-> In: $COPS_CWD"
#
export NONINTERACTIVE="${NONINTERACTIVE:-}"
export A_USE_ANSIBLE="${A_USE_ANSIBLE-}"
export QUIET="${QUIET-}"
export VERBOSE="${VERBOSE-}"
if [[ -n $VERBOSE ]];then QUIET=;fi
export NO_SILENT="${NO_SILENT-1}"
export NO_A_ARGS="${NO_A_ARGS-}"
export NO_DEFAULT_VAULTS="${NO_DEFAULT_VAULTS-}"
export SKIP_PRINT_ENV=${SKIP_PRINT_ENV-}
export SKIP_SET_CORE_VARIABLES="${SKIP_SET_CORE_VARIABLES-}"
export SKIP_COPS_COREVAULT_SETUP="${SKIP_COPS_COREVAULT_SETUP-}"
export SKIP_COPS_SETUP="${SKIP_COPS_SETUP-}"
export SKIP_COPS_INSTALL="${SKIP_COPS_INSTALL-}"
export SKIP_COPS_UPDATE="${SKIP_COPS_UPDATE-}"
export NO_SHARED_COPS="${NO_SHARED_COPS-}"
export SKIP_COPS_FROM_SYSTEM="${SKIP_COPS_FROM_SYSTEM-}"
export SKIP_COPS_CHECKOUT="${SKIP_COPS_CHECKOUT-}"
#
export COPS_ROOT="${cops_root:-$HOME/corpusops.bootstrap}"
export SYS_COPS_ROOT=${SYS_COPS_ROOT:-/srv/corpusops/corpusops.bootstrap}
export LOCAL_COPS_ROOT="${cops_path:-$COPS_LOCAL_FOLDER/corpusops.bootstrap}"
export COPS_PLAYBOOKS="${COPS_PLAYBOOKS:-${cops_playbooks:-"${LOCAL_COPS_ROOT}/roles/corpusops.roles/playbooks"}}"
export COPS_URL="${COPS_URL:-https://github.com/corpusops/corpusops.bootstrap}"
export COPS_SILENTRUN=$LOCAL_COPS_ROOT/bin/silent_run
export COPS_INSTALLER=$LOCAL_COPS_ROOT/bin/install.sh
export COPS_INSTALL_ARGS=${COPS_INSTALL_ARGS:-"-C -S"}
export COPS_UPDATE_ARGS=${COPS_UPDATE_ARGS:-"-C -s"}
#
DEFAULT_AP="$LOCAL_COPS_ROOT/bin/ansible-playbook"
DEFAULT_A_BIN="$LOCAL_COPS_ROOT/bin/ansible"
DEFAULT_A_VERBOSITY="-v"
export A_DRY_RUN=${A_DRY_RUN-${DRY_RUN-}}
export A_AP="${A_AP-$DEFAULT_AP}"
export A_BIN="${A_BIN-$DEFAULT_A_BIN}"
export A_CALLED_BIN="${A_CALLED_BIN-$A_AP}"
export A_VERBOSITY="${A_VERBOSITY-$DEFAULT_A_VERBOSITY}"
export PLAYBOOK="${PLAYBOOK-}"
export A_CUSTOM_ARGS="${A_CUSTOM_ARGS-}"
# Let a way to fallback on ansible binary
if [[ -n "$A_USE_ANSIBLE" ]];then A_CALLED_BIN=$A_BIN;fi
#
export A_VAGRANT_INVENTORY=${A_VAGRANT_INVENTORY:-$COPS_CWD/.vagrant/provisioners/ansible/inventory}
export A_GIT_SERVER="${A_GIT_SERVER:-https://github.com}"
DEFAULT_A_GIT_NAMESPACE="$(basename $(dirname $COPS_CWD))"
DEFAULT_A_GIT_PROJECT="$(basename $COPS_CWD)"
export A_GIT_PROJECT="${A_GIT_PROJECT-${DEFAULT_A_GIT_PROJECT}}"
export A_GIT_NAMESPACE="${A_GIT_NAMESPACE-${DEFAULT_A_GIT_NAMESPACE}}"
DEFAULT_A_GIT_URL="${A_GIT_SERVER}/${A_GIT_NAMESPACE}/${A_GIT_PROJECT}"
export A_GIT_URL="${A_GIT_URL:-$DEFAULT_A_GIT_URL}"
export A_VAULT_NAME="${A_VAULT_NAME-${A_ENV_NAME}}"
DEFAULT_A_VAULTS_FOLDER="$COPS_CWD/.ansible/vaults"
export A_VAULTS_FOLDER="${A_VAULTS_FOLDER-${DEFAULT_A_VAULTS_FOLDER}}"
DEFAULT_A_CRYPTED_VAULTS="$A_VAULTS_FOLDER/${A_ENV_NAME}.yml"
export A_CRYPTED_VAULTS="${A_CRYPTED_VAULTS-${DEFAULT_A_CRYPTED_VAULTS}}"
DEFAULT_A_INVENTORY_FILE=""
if [[ -n "${A_ENV_NAME}" ]];then
    DEFAULT_A_INVENTORY_FILE="$COPS_CWD/.ansible/inventory_${A_ENV_NAME}"
    if [ ! -e $DEFAULT_A_INVENTORY_FILE ];then
        if [[ "$A_ENV_NAME" == "vagrant" ]] && [ -e "$A_VAGRANT_INVENTORY" ] ;then
            DEFAULT_A_INVENTORY_FILE=$A_VAGRANT_INVENTORY
        fi
    fi
fi
A_INVENTORY_FILE_SUF=""
DEFAULT_A_INVENTORY=""
export A_INVENTORY_FILE="${A_INVENTORY_FILE-${DEFAULT_A_INVENTORY_FILE}}"
if [[ -n "${A_INVENTORY_FILE}" ]];then
    if [ -d $A_INVENTORY_FILE ];then
        A_INVENTORY_FILE_SUF=/
    fi
    DEFAULT_A_INVENTORY="-i ${A_INVENTORY_FILE}${A_INVENTORY_FILE_SUF}"
fi
A_INVENTORY="${A_INVENTORY-${DEFAULT_A_INVENTORY}}"
# Do not set inventory if redefined in $@
if echo $@ | egrep -iq -- "(( ?-i +)|(--(inventory-file|inventory)(=| )))";then
    debug "Inventory CLI switch detected, removing default one"
    A_INVENTORY=""
fi
export A_INVENTORY
#
DEFAULT_SECRET_VAULTS=""
DEFAULT_SECRET_VAULT_PREFIX="$HOME/.ansiblevault-$A_GIT_NAMESPACE.$A_GIT_PROJECT"
DEFAULT_SECRET_VAULTS=""
i="$HOME/.ansiblevault-$A_GIT_NAMESPACE.$A_GIT_PROJECT"
if [ -e "$i" ];then
    DEFAULT_SECRET_VAULTS="$DEFAULT_SECRET_VAULTS $i"
fi
if [[ -n "${A_VAULT_NAME}" ]];then
    i="$HOME/.ansiblevault-$A_GIT_NAMESPACE.$A_GIT_PROJECT.$A_VAULT_NAME"
    if [ -e "$i" ];then
        DEFAULT_SECRET_VAULTS="$DEFAULT_SECRET_VAULTS $i"
    fi
fi
export PLAYBOOK_POST_ARGS="${PLAYBOOK_POST_ARGS-}"
export PLAYBOOK_POST_CUSTOM_ARGS="${PLAYBOOK_POST_CUSTOM_ARGS-}"
export SECRET_VAULTS="${SECRET_VAULTS-$DEFAULT_SECRET_VAULTS}"
export SECRET_VAULT_PREFIX="${SECRET_VAULT_PREFIX-${DEFAULT_SECRET_VAULT_PREFIX}}"
export VAULT_PASSWORD_VARIABLES_PREFIX=${VAULT_PASSWORD_VARIABLES_PREFIX:-CORPUSOPS_VAULT_PASSWORD_}
export COREVARS_VAULT="${CORE_VAULT:-"${COPS_LOCAL_FOLDER}/corevars.yml"}"
#
DEFAULT_PLAYBOOK_PRE_ARGS="${A_VERBOSITY}"
DEFAULT_PLAYBOOK_PRE_CUSTOM_ARGS=""
if [[ -z "$NO_DEFAULT_VAULTS" ]];then
    for i in \
        "$COREVARS_VAULT" \
        "$A_VAULTS_FOLDER/default.yml" \
        "$A_VAULTS_FOLDER/app.yml" \
        "$A_VAULTS_FOLDER/$A_VAULT_NAME.clear.yml" \
        "$A_VAULTS_FOLDER/$A_VAULT_NAME.yml"
    do
        if [ -e "$i" ];then
            DEFAULT_PLAYBOOK_PRE_ARGS="$DEFAULT_PLAYBOOK_PRE_ARGS -e@$i"
        fi
    done
fi
#
export PLAYBOOK_PRE_ARGS="${PLAYBOOK_PRE_ARGS-$DEFAULT_PLAYBOOK_PRE_ARGS}"
export PLAYBOOK_PRE_CUSTOM_ARGS="${PLAYBOOK_PRE_CUSTOM_ARGS-$DEFAULT_PLAYBOOK_PRE_CUSTOM_ARGS}"
#
export PATH="$LOCAL_COPS_ROOT/bin:$LOCAL_COPS_ROOT/venv/bin:$PATH"
#
run_verbose=
if [[ -z "$NO_SILENT" ]];then run_verbose="output_in_error";fi
set_vaultpwfiles
DEFAULT_A_LAUNCH_CMD="$run_verbose $A_CALLED_BIN $vaultpwfiles\
${A_CUSTOM_ARGS-} \
${PLAYBOOK_PRE_ARGS} ${PLAYBOOK_PRE_CUSTOM_ARGS} \
${A_INVENTORY} \
$PLAYBOOK \
${PLAYBOOK_POST_ARGS} ${PLAYBOOK_POST_CUSTOM_ARGS}"
#
if [[ -n $NO_A_ARGS ]];then DEFAULT_A_LAUNCH_CMD=;fi
export A_LAUNCH_CMD=${A_LAUNCH_CMD:-${DEFAULT_A_LAUNCH_CMD}}
DEFAULT_ANSIBLE_SSH_ARGS="-C -o ControlMaster=auto -o ControlPersist=60s"
DEFAULT_VAGRANT_ANSIBLE_SSH_ARGS="$DEFAULT_ANSIBLE_SSH_ARGS -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes"
if [[ -z "${A_NO_SSH_ARGS_DEFAULTS-}" ]]; then
    if [[ "$A_ENV_NAME" == "vagrant" ]]; then
        ANSIBLE_SSH_ARGS=${ANSIBLE_SSH_ARGS-${DEFAULT_VAGRANT_ANSIBLE_SSH_ARGS}}
        ANSIBLE_HOST_KEY_CHECKING=${ANSIBLE_HOST_KEY_CHECKING-"false"}
    fi
fi
if [[ -n ${ANSIBLE_SSH_ARGS-} ]];then
    export ANSIBLE_SSH_ARGS
fi
if [[ -n ${ANSIBLE_HOST_KEY_CHECKING-} ]];then
    export ANSIBLE_HOST_KEY_CHECKING
fi
